export const ModalActionTypes = {
  TOGGLE_MODAL: 'TOGGLE_MODAL',
  POPULATE_MODAL_DATA: 'POPULATE_MODAL_DATA',
  CLEAR_MODAL_DATA: 'CLEAR_MODAL_DATA',
  POPULATE_CARD_STATUS: 'POPULATE_CARD_STATUS',
};
